## SCRIPT: marker genes check

## 28.11.21 Laura Sudupe , git @lsudupe

#Libraries-------------------------------------------------
source("packages.R")
source("marker_genes.R")

###Read data

a<- readRDS("./objects/processed/integrated.sct.rds")

###Plot and save heatmap
file.path("./results/genes/marker_genes_check",filename = "Macrophagues feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = Macrophagues, size = 3)
dev.off()
png("Schwann.cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = Schwann.cells, size = 3)
dev.off()
png("DC.like.cells cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = DC.like.cells, size = 3)
dev.off()
png("Fibro cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = fibroblast, size = 3)
dev.off()
png("Circulation fibro cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = circulation.fibroblast, size = 3)
dev.off()
png("Mehotelial cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = meshotelial, size = 3)
dev.off()
png("Pericytes cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = pericytes, size = 3)
dev.off()
png( "Adipocytes cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = adipocytes, size = 3)
dev.off()
png("Neuronal cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = neuronal, size = 3)
dev.off()
png("Myeloid cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = myeloid, size = 3)
dev.off()
png("Lymphoid cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = lymphoid, size = 3)
dev.off()
png("Inmune cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = imnume, size = 3)
dev.off()
png("Cardiomyocites cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = cardiomyocite, size = 3)
dev.off()
png("Atrial cardiomyocites fibro cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = atrial.cardiomyocytes, size = 3)
dev.off()
png("Ventricular cardiomyocites cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = ventricular.cardiomyocytes, size = 3)
dev.off()
png("Injury dilated cardiomyocites cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = injury.dilated.cardiomyopathy, size = 3)
dev.off()
png("Injury coronary disease cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = injury.coronary.disease, size = 3)
dev.off()
png("Endohtelial cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = endothelial, size = 3)
dev.off()
png("Endothelial lymphatic cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = endothelial.lymphatic.vessel, size = 3)
dev.off()
png("Endothelial vein cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = endothelial.vein, size = 3)
dev.off()
png("Endothelial artery cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = endothelial.artery, size = 3)
dev.off()
png("Injury endothelial cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = injury.endothelial, size = 3)
dev.off()
png("Smooth muscle cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = smooth.muscle, size = 3)
dev.off()
png("B cell cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = B.cell, size = 3)
dev.off()
png("NK cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = lymphoid.NK, size = 3)
dev.off()
png("Machofage/monocytes cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = machofage.monocytes, size = 3)
dev.off()
png("T cells feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = T.cell, size = 3)
dev.off()
png("Neutrophils feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = neutrophils, size = 3)
dev.off()
png("Dentritic feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = dentritic, size = 3)
dev.off()
png("granulocytes feature integrated H.png")
DoHeatmap(subset(a, downsample = 100), features = granulocytes, size = 3)
dev.off()