## SCRIPT: marker genes check

## 28.11.21 Laura Sudupe , git @lsudupe

#Libraries-------------------------------------------------
source("packages.R")
source("marker_genes.R")

###Read data

a<- readRDS("./objects/processed/integrated.sct.rds")

###Plot and save heatmap
png(file.path("./results/genes/marker_genes_check",filename = "Macrophagues feature.png"))
DoHeatmap(subset(a, downsample = 100), features = Macrophagues, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename = "Schwann.cells feature.png"))
DoHeatmap(subset(a, downsample = 100), features = Schwann.cells, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="DC feature.png"))
DoHeatmap(subset(a, downsample = 100), features = DC.like.cells, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Fibro feature.png"))
DoHeatmap(subset(a, downsample = 100), features = fibroblast, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Circulation fibro feature.png"))
DoHeatmap(subset(a, downsample = 100), features = circulation.fibroblast, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Mehotelial feature.png"))
DoHeatmap(subset(a, downsample = 100), features = meshotelial, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Pericytes feature.png"))
DoHeatmap(subset(a, downsample = 100), features = pericytes, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Adipocytes feature.png"))
DoHeatmap(subset(a, downsample = 100), features = adipocytes, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Neuronal feature.png"))
DoHeatmap(subset(a, downsample = 100), features = neuronal, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Myeloid feature.png"))
DoHeatmap(subset(a, downsample = 100), features = myeloid, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Lymphoid feature.png"))
DoHeatmap(subset(a, downsample = 100), features = lymphoid, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Inmune feature.png"))
DoHeatmap(subset(a, downsample = 100), features = imnume, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Cardiomyocites feature.png"))
DoHeatmap(subset(a, downsample = 100), features = cardiomyocite, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Endohtelial feature.png"))
DoHeatmap(subset(a, downsample = 100), features = endothelial, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Smooth muscle feature.png"))
DoHeatmap(subset(a, downsample = 100), features = smooth.muscle, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="B cell feature.png"))
DoHeatmap(subset(a, downsample = 100), features = B.cell, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="NK feature.png"))
DoHeatmap(subset(a, downsample = 100), features = lymphoid.NK, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Machofage/monocytes feature.png"))
DoHeatmap(subset(a, downsample = 100), features = machofage.monocytes, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="T cells feature.png"))
DoHeatmap(subset(a, downsample = 100), features = T.cell, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Neutrophils feature.png"))
DoHeatmap(subset(a, downsample = 100), features = neutrophils, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Dentritic feature.png"))
DoHeatmap(subset(a, downsample = 100), features = dentritic, size = 3)
dev.off()
png(file.path("./results/genes/marker_genes_check",filename ="Granulocytes feature.png"))
DoHeatmap(subset(a, downsample = 100), features = granulocytes, size = 3)
dev.off()
